version: '3.3'
services:
  frontend:
    image: lucj/kernelci-frontend
    depends_on:
      - redis
    ports:
      - 80:80
    volumes:
      - ./kernelci-frontend/etc/flask_settings:/etc/linaro/kernelci-frontend.cfg
    restart: always
  proxy-backend:
    image: lucj/kernelci-proxy-backend
    depends_on:
      - backend
    ports:
      - 8000:80
    restart: always
  backend:
    image: lucj/kernelci-backend
    depends_on:
      - mongo
      - redis
    ports:
      - 8001:8888
    restart: always
  redis:
    image: redis:3.2
    restart: always
  mongo:
    image: mongo:3.4
    restart: always
