version: '3.3'
services:
  # tls:
  #   image: traefik
  #   ...
  frontend:
    build: ./kernelci-frontend
    ports:
      - 8001:80
  # backend:
  #   build: ./kernelci-backend
  #   ports:
  #     - 8000:80
  # celery:
  #   image: celery:4.0.2
  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data
  rabbitmq:
    image: rabbitmq:3.6
  mongo:
    image: mongo:3.4
    volumes:
      - mongo-data:/data/db
  kibana:
    image: kibana:5.5
    ports:
      - 5601:5601
  elasticsearch:
    image: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
volumes:
  redis-data:
  mongo-data:
  elasticsearch-data:
