version: '3.3'
services:
  # proxy:
  #   image: traefik
  #   ...
  frontend:
    build: ./kernelci-frontend
    ports:
      - 80:80
    volumes:
      - ./kernelci-frontend/etc/flask_settings:/etc/linaro/kernelci-frontend.cfg
  proxy-backend:
     build: ./proxy-backend
     ports:
       - 8090:80
  backend:
     build: ./kernelci-backend
     depends_on:
       - mongo
       - redis
     ports:
       - 8091:8888
  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data
  mongo:
    image: mongo:3.4
    volumes:
      - mongo-data:/data/db
  kibana:
    image: kibana:5.5
    ports:
      - 5601:5601
  elasticsearch:
    image: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
volumes:
  redis-data:
  mongo-data:
  elasticsearch-data:
