version: '3.3'
services:
  frontend:
    build: ./kernelci-frontend
    depends_on:
      - redis
    ports:
      - 80:80
    restart: always
  proxy-backend:
    build: ./proxy-backend
    depends_on:
      - backend
    ports:
      - 8000:80
    restart: always
  backend:
    build: ./kernelci-backend
    depends_on:
      - mongo
      - redis
    ports:
      - 8001:8888
    restart: always
  redis:
    image: redis:3.2
    restart: always
  mongo:
    image: mongo:3.4
    restart: always
